### PR TITLE
Customizable metadata style for 4:3 aspect ratio

### PR DESCRIPTION
**Pull request by chrizzo-hb**
Hi there! Sorry to bother you again, but I had another "bright" idea. We already talked about this on Discord - I wanted to change which details are displayed in the gamelist (because I'd prefer total game time over the community rating, I kinda like to track how much time I spend with certain games).

Again, no hard feelings if you decline this PR, obviously! Again, I was just tinkering out of curiosity (and for my own personal use) and felt like I could make it available to you, in case you're interested?

I basically followed your suggestion and introduced 3 different `Game Metadata Styles`:

* `History` (same as `Default`) shows **release date** and **community rating**
* `Stats` shows **play count** and **game time**
* `History/Stats` shows **release date** and **game time** (that's the one I actually wanted for myself!)

I tried my best to calculate the positions of the additional icons/texts precisely to fit them into you design. However, I am **not** sure if everything is **exactly** where **you** would've placed it, so maybe try it out and adjust a bit, if you feel like I misplaced something.

Unfortunately, I could only do it for the 4:3 aspect ratio, simply because I dont have a 1:1 aspect ratio screen available. (The other aspect ratios seem to have all metadata values anyway, only 4:3 and 1:1 have the "short" version with only 2 values.) I could've tried to calculate the numbers in the same way I did for the 4:3 resolution, however, I wouldn't have been able to verify that it actually looks right. I tried switching to 1:1 on my H, however, that just messes up spacing on the home screen, so I gave up on that idea, sorry!

Well... that's it. Have a look if you'd like! If you wanna pick it up, feel free to tell me what to change, I'm open to suggestions, as always! :)

### CODE REVIEW

**Comment by anthonycaccese** [comment]
thinking through this my initial thinking is to see if would could make sense to incorporate this switch into the existing `gamelist-view-metadata` subset.  something like "stats focus" or "history focus" and use those terms to group metadata for what should display.  That could work across all aspect ratios too.

**Comment by chrizzo-hb** [comment]
I agree, that sounds like a great idea and it would reduce the clutter! Maybe something like this? (I'd still need the "mixed" option though because I reeeeaaally want to have release date and game time, those are the 2 things I actually want to see, that's what I'm doing it all for! 😁)

However, would this also be update-friendly? Because most people would've set it to either "on" or "off" by now, so after an update, they would have a selected option that isn't viable anymore. How would the theme behave then? Go to "default" anyway if "on" doesn't exist anymore? It should, right?

```
   <!--
   ///
   Subset: Game Metadata
   ///
   -->
   <subset name="gamelist-view-metadata" displayName="Game Metadata">
      <include name="default" displayName="Default" />
      <include name="history" displayName="History Focus" />
	  <include name="stats" displayName="Stats Focus" />
	  <include name="mixed" displayName="Mixed Focus" />
	  <include name="off" displayName="Off" />
   </subset>
```

**Comment by anthonycaccese** [comment]
for update friendliness was thinking we could do something like this...
```
<subset name="gamelist-view-metadata" displayName="Game Metadata">
   <include name="on" displayName="On" />
   <include name="on-history" displayName="On (History Focus)" />
   <include name="on-stats" displayName="On (Stat Focus)" />
   <include name="on-mixed" displayName="On (Mixed Focus)" />
   <include name="off" displayName="Off" />
</subset>
```
That would keep the on and off options that users have today in place while adding the net new options (the value that is key to that is `name`)

**Comment by chrizzo-hb** [comment]
I tried the other solution like 15 minutes ago and I can confirm that it works - the theme just switched from "on" to "default" automatically after I replaced the original code with the one I proposed earlier. However, if you like your solution more, we can totally do that, I don't mind, it's fine with me either way.

Did you see the additional change I made a couple of minutes ago? Maybe check on Discord, I posted a picture... I figured out how to display the game time like HH:MM:SS instead of this stupid mind numbing string that says like 10h 34mn... and gets cut off in the middle anyway... way more compact an readable I think.

**Comment by anthonycaccese** [comment]
there isn't that much of a difference between those approaches =).   My preference though would be for the displayed value to be "On" or "Off" to indicate if the setting it turning the display on or off.

**Comment by chrizzo-hb** [comment]
Already done! 👍 It's your theme, man, I'm happy to name values however you want them! 😊 I'm really just happy to learn and participate!

**Comment by anthonycaccese** [comment]
And I am glad for your help and ideas.  Will try to get into review of this hopefully in the next few days.

**Comment by anthonycaccese** [comment]
on idea i want to explore is "does this toggle only make sense for 4:3 and 1:1" aspect ratios and if so... does it make sense to only show these new options if one of those aspect ratios is selected.   That would be a way to only show options that make a visible change in the theme+aspect ratio combo (and could help avoid questions for users say on 16:9 that ask what the option changes)

**Comment by chrizzo-hb** [comment]
I agree! I actually had a similar idea, but I gave it up, maybe a little to early.

In my very first draft when I still had "metadata style" as a separated subset, I actually tried to make the whole subset only visible if auto detected aspect ratio is 4:3, basically copying the condition from the code above. It worked in the sense that it was hidden on my device/TV as expected. However, when the subset was completely missing, everything seemed to default to "true", so I saw all of the icons and texts above each other, making a huge mess.

Now that the "focus" options have been moved as additional options for "metadata" instead, I could try adding the condition only to the new "focus" includes instead. I guess that should work because if they are missing, "metadata" would still default to "default", so no harm done. I might try that tonight!

(Again, no rush, I'm just curious and I have some time to spare right now!)

However, I wonder if we need to take into consideration that someone might manually set aspect ratio to whatever. The subset conditions seem to be evaluted when the menu is opened, so if you manually set aspect ratio to 4:3 to override auto, the options will not magically appear unless you close and re-open the menu. I am pretty confident of that, because I think I tried that, I hope I remember correctly. I think I purposely made a version where my subset was only shown for **manual 4:3** just to see how it behaves and it only showed up after I reopened the menu again, I think.

On the other hand, the documentation clearly says that people should rely on auto-detect and only use manual toggle as a last resort, so maybe hiding the options on incompatible autodetected aspect ratio (to avoid confusion) beats the importance of showing the options for the rare case of someone switching to 4:3 manually and expexting the options to be shown?

Does that train of thought make any sense?

**Comment by chrizzo-hb** [comment]
I can confirm that this

```
   <!--
   ///
   Subset: Game Metadata
   ///
   -->
   <subset name="gamelist-view-metadata" displayName="Game Metadata">
      <include name="on" displayName="On" />
      <include ifSubset="aspect-ratio:4-3|4-3-auto|1-1|1-1-auto" name="on-history" displayName="On (History Focus)" />
	  <include ifSubset="aspect-ratio:4-3|4-3-auto|1-1|1-1-auto" name="on-stats" displayName="On (Stat Focus)" />
	  <include ifSubset="aspect-ratio:4-3|4-3-auto|1-1|1-1-auto" name="on-mixed" displayName="On (Mixed Focus)" />
	  <include name="off" displayName="Off" />
   </subset>
```

works on my RG35XX H as expected:

* shows the focused options on the built-in screen (4:3) on auto
* hides the options on the built-in screen (4:3) after switching to 16:9 manually **and reloading the menu**
* hides the options on my TV (16:9) on auto
* shows the focused options on my TV (16:9) after switching to 4:3 manually **and reloading the menu**
* defaults to "on" when the focused options are not available (even if they are currently selected)
* returns to the previously selected focus option after being connected to my 16:9 TV via HDMI where the option would not be available (unless I go to the menu and change it there, obviously)

I think it would be a legit solution. I committed it, however, feel free to revert, that's what git is for. :)

**Comment by anthonycaccese** [comment]
I made time this weekend to revisit this and thought of a different way I would like to implement it.  I made the changes in this branch if you are interested in checking them out: https://github.com/anthonycaccese/art-book-next-es/tree/play-stats

I was interested in using the new stackpanel component which helps make the metadata row a bit more dynamic spacing wise. 

Here are some screenshots of it in action.

screenshot-2024-07-20_19h4622
screenshot-2024-07-20_19h4757
screenshot-2024-07-20_19h4902

What do you think?

**Comment by chrizzo-hb** [comment]
I'm a bit sad that none of my commits will make it to the final solution. ;) Aside of that, I like it!

One thing that makes me worry though: What if someone spends more than a day with a game? (I actually spent more than one day with The Minish Cap!) Let's just say someone is *wildly* enthusiastic for Fix-It-Felix and plays it for a hundred days... wont that break your 3-in-a-row design?

DSC_5921

**Comment by anthonycaccese** [comment]
There will space for more commits for sure =)

I haven't been able to figure out a different way to format the seconds to trim them so in this case what would happen is the number would be truncated with elipses.   I could remove playcount if its not needed as another option.

**Comment by chrizzo-hb** [comment]
Sorry, it was a rhetorical question... I am a bit tired, it's 3 am, I spent most of the day helping a friend tearing down walls, literally. I should have phrased it better, I'm sorry. :(

But yeah, I kinda wanted to point out that I assume with your design from the screenshots, it might get a little too crowded when the play time gets too long, so it might get cut off (or possibly break the layout, depending on how that new stackpanel stuff works, I have no idea about that, hence the vague, partly rhetorical question).

Now, I was curious, so I just threw your branch version on my new 40 to try it out real quick since my Minish Cap play time exceeds 24 hours. And yeah, a lot of the playtime gets cut off, rendering the result looking not very informative anymore (full length string would be `01 01:17:01`).

DSC_6003

Personally, I'd prefer the releasedate/playtime combination with enough space for both to be fully readable - I started this whole thing because I wanted specifically that. But it's your theme, mate, if you prefer to have the count in there, too, I could always fork and take it over again, muahahahaha! ;)

I also tried to cut off seconds when I tinkered with this, too, by the way. But I couldn't find a way. I didn't find the necessary string operations available to pull that off, otherwise I would've totally dropped them, maybe even made sure that every game that hasn't been played for a whole minute isn't considered to have been "played" at all. ;) (Actually, I wish ES would just provide a date formatter interface that takes a string like `"hh:mm"` or whatever to give the theme designers the power of deciding themselves. But I am a Java/CoffeeScript developer, so maybe I'm a little too used to stuff like this.

I didn't get to check out your code, yet, I would love to, just to learn, compare your approach to mine, see what you did different. But I wont be able to get to it before Wednesday or Thursday, I'm sorry, I'll be out of town, I'm actually just still awake because I'm packing. :D

**Comment by anthonycaccese** [comment]
Hope you have a great trip!

I found another way to help with the display of the duration (and it was staring me in the face the whole time)

We can use "expandseconds" instead and when doing so it will format the playtime relatively (e.g. 1 d 23 h 4 mn)

I think this works nicely.  And also decided to remove the release date info when in "play stats" mode to give more space.  I think it makes sense to focus on stats in this case.

Preview:

A game that has never been played (I hide the playcount in this case):
screenshot-2024-07-21_13h1244

A game played for a few mins:
screenshot-2024-07-21_13h1203

A game played for a few hours:
screenshot-2024-07-21_13h1151

A game played for a few days:
screenshot-2024-07-21_13h1146

Updated the branch with the latest: https://github.com/anthonycaccese/art-book-next-es/tree/play-stats

I think this looks pretty good and am thinking to commit it to the main branch.  Let me know what you think.

**Comment by chrizzo-hb** [comment]
Thanks! I'm with my brother and his family in the countryside, visiting our aunt. Tomorrow we're taking my niece to the zoo!!!

I think I initially used the predefined `md_gametime` which always got cut off, slicing numbers, doing `1d 2h 5...` instead of cutting in a useful place like `1d 2h`. That's why I switched to the mode that has `DDD HH:MM:SS`. I never tried using `expandseconds` directly, if that cuts off reasonable (like your screenshots suggest) I think it's perfect!!!!! Looks really good, too!! I did something similar with "never played", too! Looks good!!

As I said before regarding the modes: I purposely made 3 modes to switch between:

* History focus (release, rating) (default)
* Stats focus (play count, game time)
* Mixed focus (release, game time)

Because I, personally, wanted the **last one (release, game time)** and I made the others for those who'd like them. But it's OK for me if you don't wanna include that, I can still fork my own, I don't mind, really!! It's just that out of the five metadata options, those two are the only ones I care about.

**Comment by anthonycaccese** [comment]
Nice, I was wondering who the Mixed focus was for =).  I can add that in no problem.  Will do that this week.

**Comment by anthonycaccese** [comment]
Added a mixed option just now - also changed the names in the options to explicitly indicate what they will show (thought that might be helpful).

**Comment by chrizzo-hb** [comment]
Thank you so much!!! ❤️

**Comment by chrizzo-hb** [comment]
I will try it out as soon as I'm back home!

**Comment by anthonycaccese** [comment]
going to merge my changes today.  its looking good.  will close out this PR

**Comment by anthonycaccese** [comment]
changes added through this PR: https://github.com/anthonycaccese/art-book-next-es/pull/20

**Pull request closed without merging**
